fix: make conf return errors messages again

diff --git a/dot_scripts/bin/executable_conf b/dot_scripts/bin/executable_conf
--- a/dot_scripts/bin/executable_conf
+++ b/dot_scripts/bin/executable_conf
@@ -3,7 +3,10 @@ config_directory="$1"
 config_path="$XDG_CONFIG_HOME/$config_directory"
 
 if [[ -d $config_path ]]; then
-    cd "$config_path" || echo "Failed to find directory" exit 1
+    cd "$config_path" || return
     nvim "$config_path"
-    cd - || exit 1
+    cd - || return
+else
+    echo "Failed to find directory: $config_path"
+    exit 1
 fi
